version: '3'

services:
  proxy:
    build:
      context: ./
      dockerfile: ./docker/production/proxy/Dockerfile
    image: metagrid_production_proxy
    networks:
      - traefik_default
      - default
    container_name: proxy
    env_file:
      - .envs/.production/.proxy
    volumes:
      - './:/app'
    ports:
      - '3001:3001'

  react:
    build:
      context: ./
      dockerfile: ./docker/production/react/Dockerfile
    image: metagrid_production_react
    networks:
      - traefik_default
      - default
    container_name: react
    env_file:
      - .envs/.production/.react
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - proxy

networks:
  traefik_default:
    external: true
