exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  # FRONTEND
  # ------------------------------------------------------------------------------
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        files: .+(js|jsx|ts|tsx|css|sass|less|json)
        entry: yarn --cwd frontend precommit

  # BACKEND
  # ------------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: ["--config=backend/setup.cfg"]
        additional_dependencies:
          - isort<5 # https://github.com/gforcada/flake8-isort/issues/88

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
