stages:
  - lint
  - test

variables:
  POSTGRES_USER: "metagrid"
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: "test_metagrid"

flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8 --max-line-length=120 --ignore=E203,E501,F,W --max-complexity=18 --exclude=.tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules,.idea,.mypy_cache,.pytest_cache,*__init__.py

pytest:
  stage: test
  image: python:3.7
  tags:
    - docker
  services:
    - postgres:11
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB

  before_script:
    - pip install -r backend/requirements/local.txt

  script:
    - pytest
