stages:
  - lint
  - test

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# https://docs.gitlab.com/ee/ci/caching/#caching-python-dependencies
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
- python -V               # Print out python version for debugging
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate

variables:
  POSTGRES_USER: "metagrid"
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: "test_metagrid"
  # https://gitlab.com/gitlab-org/gitlab/issues/206944
  POSTGRES_HOST_AUTH_METHOD: trust

flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8 --config=backend/setup.cfg

pytest:
  stage: test
  image: python:3.7
  tags:
    - docker
  services:
    - postgres:11
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
    CELERY_BROKER_URL: redis://redis:6379/0

  before_script:
    - pip install -r backend/requirements/local.txt

  script:
    - pytest backend
