stages:
  - lint
  - test

variables:
  POSTGRES_USER: "metagrid"
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: "test_metagrid"
  # https://gitlab.com/gitlab-org/gitlab/issues/206944
  POSTGRES_HOST_AUTH_METHOD: trust

flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8 --config=backend/setup.cfg

pytest:
  stage: test
  image: python:3.7
  tags:
    - docker
  services:
    - postgres:11
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
    CELERY_BROKER_URL: redis://redis:6379/0

  before_script:
    - pip install -r backend/requirements/local.txt

  script:
    - pytest backend/
