version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: metagrid_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  django:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: metagrid_production_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "5000:5000"
    command: /start

  traefik:
    build:
      context: .
      dockerfile: ./docker/production/traefik/Dockerfile
    image: metagrid_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
